---
- name: Ensure bash aliases
  ansible.builtin.lineinfile:
    path: "{{ ansible_user_dir }}/.bash_aliases"
    line: "alias {{ item.key }}='{{ item.value }}'"
    regexp: "^alias {{ item.key }}="
    create: true
    state: "{{ item.state | default(omit) }}"
  loop: "{{ bash_aliases | default({}) | dict2items | unique }}"
  loop_control:
    label: "alias {{ item.key }}='{{ item.value }}'"

- name: Ensure proxy environment
  ansible.builtin.blockinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    block: |-
      {% if http_proxy is defined %}
      http_proxy="{{ http_proxy }}"
      HTTP_PROXY="{{ http_proxy }}"
      {% endif %}
      {% if https_proxy is defined or http_proxy is defined %}
      https_proxy="{{ https_proxy | default(http_proxy) }}"
      HTTPS_PROXY="{{ https_proxy | default(http_proxy) }}"
      {% endif %}
      {% if no_proxy is defined %}
      no_proxy="{{ (no_proxy.split(',') if no_proxy is string else no_proxy) |
      map('regex_replace', '^(?:[0-9]{1,3}\.){1,3}.*') | select() |
      map('regex_replace', '^\*') | join(',') }}"
      NO_PROXY="{{ (no_proxy.split(',') if no_proxy is string else no_proxy) |
      map('regex_replace', '^(?:[0-9]{1,3}\.){1,3}.*') | select() |
      map('regex_replace', '^\*') | join(',') }}"
      {% endif %}
    marker: "# {mark} PROXY SETTINGS"
