---
- name: Ensure bash aliases
  ansible.builtin.lineinfile:
    path: "{{ ansible_user_dir }}/.bash_aliases"
    line: "alias {{ item.key }}='{{ item.value }}'"
    regexp: "^alias {{ item.key }}="
    create: true
    state: "{{ item.state | default(omit) }}"
  loop: "{{ bash_aliases | default({}) | dict2items | unique }}"
  loop_control:
    label: "alias {{ item.key }}='{{ item.value }}'"
