---
- name: Ensure Byobu directory
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/byobu"
    recurse: true
    state: directory

- name: Ensure TMUX renaming in Byobu
  ansible.builtin.lineinfile:
    path: "{{ ansible_user_dir }}/.config/byobu/profile.tmux"
    line: "{{ item }}"
    create: true
    state: "{{ 'present' if tmux_rename_window | default(false) else 'absent' }}"
  loop:
    - 'source $BYOBU_PREFIX/share/byobu/profiles/tmux'
    - 'set-option -g allow-rename on'
