---
- name: Ensure Byobu directory
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/byobu"
    recurse: true
    state: directory

- name: Ensure TMUX renaming in Byobu
  ansible.builtin.lineinfile:
    path: "{{ ansible_user_dir }}/.config/byobu/profile.tmux"
    line: "{{ item.line | mandatory }}"
    insertafter: "{{ item.insertafter | default(omit) }}"
    insertbefore: "{{ item.insertbefore | default(omit) }}"
    create: true
    state: "{{ item.state | default(omit) }}"
  loop:
    - line: 'source $BYOBU_PREFIX/share/byobu/profiles/tmux'
      insertbefore: BOF
      state: present
    - line: 'set-option -g allow-rename on'
      state: "{{ 'present' if tmux_rename_window | default(false) else 'absent' }}"
