---
- name: Enumerate Firefox policies
  ansible.builtin.set_fact:
    firefox_policies: "{{ lookup('template', 'firefox.yml.j2') | from_yaml }}"

- name: Handle Firefox policies
  become: true
  block:
    - name: Ensure Firefox directories
      ansible.builtin.file:
        path: /etc/firefox/policies
        state: directory

    - name: Ensure Firefox policies
      ansible.builtin.copy:
        content: "{{ {'policies': firefox_policies} | to_nice_json }}"
        dest: /etc/firefox/policies/policies.json
        owner: root
        group: root
        mode: 0644
  when: firefox_policies is mapping
