---
- name: Ensure lastpass-cli environment
  ansible.builtin.lineinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    line: "export LPASS_{{ item.key | upper }}='{{ item.value }}'"
    regexp: "^export LPASS_{{ item.key | upper }}="
    state: "{{ item.state | default(omit) }}"
  loop: "{{ lpass_env | default({}) | dict2items }}"
  loop_control:
    label: "{{ item.key }}='{{ item.value }}'"

- name: Ensure lastpass-cli scripts
  ansible.builtin.copy:
    src: "/usr/share/doc/lastpass-cli/examples/{{ item }}"
    dest: "{{ ansible_user_dir }}/.local/bin/{{ item }}"
    mode: '0755'
    remote_src: true
  loop: "{{ lpass_scripts | default([]) }}"
