---
- name: Ensure listadmin configuration
  ansible.builtin.template:
    src: 'listadmin.ini.j2'
    dest: "{{ ansible_user_dir }}/.listadmin.ini"
    mode: '0600'
  when: listadmin_lists | default(None) | type_debug == 'list'
