---
- name: Ensure motd-news state
  become: true
  ansible.builtin.lineinfile:
    path: /etc/default/motd-news
    regexp: '^ENABLED='
    line: "ENABLED={{ motd_news | bool | int }}"
  when: motd_news is defined
